apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 1
  image: vault:1.3.2
  bankVaultsImage: banzaicloud/bank-vaults:0.9.0
  serviceAccount: vault
  serviceType: ClusterIP
  ingress:
    annotations:
    spec: {}
  volumes:
    - name: vault-file
      emptyDir: {}
  volumeMounts:
    - name: vault-file
      mountPath: /vault/file
  unsealConfig:
    kubernetes:
      secretNamespace: vault
  statsdDisabled: true
  serviceMonitorEnabled: false
  vaultLabels:
    kv_version: v1
  config:
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    ui: false
    api_addr: https://vault:8200
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret-v1/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
          path "secret-v2/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: kms-vault-operator
            bound_service_account_names: kms-vault-operator
            bound_service_account_namespaces: vault
            policies: [ allow_secrets ]
            ttl: 5m
      - type: approle
        roles:
        - name: app-role
          token_policies:
          - allow_secrets
          token_ttl: 1h
    secrets:
      - path: secret-v1
        type: kv
        description: General secrets v1.
        options:
          version: 1
      - path: secret-v2
        type: kv
        description: General secrets v2.
        options:
          version: 2