apiVersion: v1
kind: Service
metadata:
  name: vault-ext
  namespace: vault
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
    nodePort: 30028
  selector:
    app.kubernetes.io/name: vault
  type: NodePort